services:
  - type: web
    name: keras-image-api  # ← 任意のアプリ名に変更してOK
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true